os: Visual Studio 2015
image: Visual Studio 2015

platform:
  - x64
  - x86

environment:
  global:
    REPO_DIR: zfp
    PACKAGE_NAME: zfpy
    BUILD_COMMIT: 739ea17c002eb471e0e945a87f2bfae7a791c71c
    BUILD_DEPENDS: "cython numpy"
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD:
        secure: "j/xESWIkkgjZKJhieZta5lYn71FRvHrpwx5XNWoj5A4yaFuXfNNKVMOs2tm488lr7NSVvpaa3+dRhYV91AteeKgn9H/ZwauqdgCQz8Ee9oEHy+NH6j4zQJHls4Fbn0QormFzLtGA8VcFAkQhnDRSu8canTcBeomhylAXe1W5vSid3iafkiMXn4SZQc/v6LfQvPuRwwmNafnB7lLELyl/Lj5C2HuEte4fk2qGGoJCg5hs/ynmzW4PrvtT5Up0boKxJTFwxr1NPVJJF2Hcklbd2A=="

  matrix:
    - PYTHON: C:\Python35
      PYTHON_VERSION: 35

    - PYTHON: C:\Python36
      PYTHON_VERSION: 36

    - PYTHON: C:\Python37
      PYTHON_VERSION: 37

    - PYTHON: C:\Python38
      PYTHON_VERSION: 38

install:
    - IF "%platform%" == "x64" SET PYTHON=%PYTHON%-x64
    - git clone https://github.com/LLNL/zfp.git

    # Check that we have the expected version and architecture for Python
    - SET PATH=%PYTHON%;%PYTHON%\Lib;%PYTHON%\Libs;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%
    - python --version
    - python -m pip install pip
    - python -m pip install --upgrade pip
    - python -m pip install twine setuptools wheel cython numpy scikit-build
    - IF %PYTHON_VERSION% == "35" python -m pip install "cmake<3.14"
    - IF %PYTHON_VERSION% == "36" python -m pip install "cmake<3.14"
    - IF %PYTHON_VERSION% == "37" python -m pip install "cmake<3.14"
    - IF %PYTHON_VERSION% == "38" python -m pip install cmake

    - echo %PATH%
    - echo %PYTHON%
    - ls %PYTHON%\libs
    - ls %PYTHON%\Include
    - ls %PYTHON%\lib\site-packages\numpy\core\include\numpy

    # Set some variables to be used in the build
    - python -c "from distutils import sysconfig; print(sysconfig.get_config_var('LIBDIR'))"
    - python -c "from sysconfig import get_paths; print(get_paths()['include'])"
    - python -c "import numpy; print(numpy.get_include())"

before_build:
    - set generator="Visual Studio 14 2015"
    - IF "%platform%" == "x64" set generator="Visual Studio 14 2015 Win64"

build_script:
    - cd %REPO_DIR%
    - git checkout %BUILD_COMMIT%
    - mkdir build
    - cd build
    - cmake .. -G %generator% -DBUILD_ZFPY=ON -DBUILD_TESTING=OFF -DPYTHON_EXECUTABLE=%PYTHON%\python -DPYTHON_LIBRARY=%PYTHON%\Libs\python%PYTHON_VERSION%.lib -DPYTHON_INCLUDE_DIR=%PYTHON%\Include -DPYTHON_NUMPY_INCLUDE_DIR=%PYTHON%\lib\site-packages\numpy\core\include -DBUILD_SHARED_LIBS=OFF
    - cmake --build . --config Release
    - cd ..
    - ls build
    - ls build/bin
    - python setup.py bdist_wheel

deploy_script:
  - python -m twine upload --repository-url https://upload.pypi.org/legacy/ --skip-existing dist/*
